services:
  db:
    image: postgres:latest
    container_name: db_acmevita_api
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=acmevita_api
    restart: unless-stopped
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:latest
    container_name: redis_acmevita_api
    user: "100:101"
    expose:
      - "6379"
    command: ["redis-server", "--appendonly", "no", "--maxclients", "25000"]
    read_only: true
    tmpfs:
      - /tmp
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    cap_drop: ["ALL"]
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
        reservations:
          cpus: "0.10"
          memory: 32M
  nginx:
    image: nginx:latest
    container_name: nginx_acmevita_api
    cap_drop: ["ALL"]
    cap_add: ["NET_BIND_SERVICE", "CHOWN", "SETGID", "SETUID"]
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - redis
      - app
    networks:
      - proxy
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 128M
        reservations:
          cpus: "0.05"
          memory: 64M
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acmevita_api
    user: "app"
    environment:
      - REDIS_URL=redis://redis:6379
      - RATE_LIMIT_ENABLED=true
      - DB_URL=postgresql://postgres:postgres@db:5432/acmevita_api
    tmpfs:
      - /tmp
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop: ["ALL"]
    read_only: true
    networks:
      - backend
      - proxy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M

networks:
  backend:
    internal: true
  proxy:
    driver: bridge
